const carreras = [
  "Fotografía – Tecnología de la Imagen",
  "Diseño Gráfico",
  "Inglés como Lengua Extranjera",
  "Administración del Comercio Exterior",
  "Administración y Gestión de Recursos Humanos",
  "Administración Aduanera",
  "Compras y Control de Inventarios – Logística Internacional",
  "Gestión de Empresas de Hospedaje y Gastronómicas",
  "Gestión Empresarial – Gestión y Administración Empresarial",
  "Gestión de Grupos Turísticos – Gestión Ecoturística",
  "Contabilidad y Finanzas – Contaduría Pública",
  "Asistencia Administrativa",
  "Ingeniería en Acuicultura",
  "Ingeniería en Sistema de Producción Animal – Sistemas de Producción Animal – Producción Animal.",
  "Ingeniería Agronómica con énfasis en riego y drenaje – Producción Agropecuaria Bajo Riego",
  "Manejo Forestal y Vida Silvestre",
  "Asistencia Veterinaria",
  "Mediación Pedagógica",
  "Enseñanza de la Especialidad Técnica",
  "Ingeniería en Producción Industrial.",
  "Ingeniería Electrónica",
  "Ingeniería Electromecánica",
  "Ingeniería Eléctrica – Electricidad",
  "Control de Calidad – Ingeniería en Procesos y Calidad",
  "Ingeniería en Gestión Ambiental",
  "Ingeniería en Manejo del Recurso Hídrico",
  "Ingeniería en Salud Ocupacional y Ambiente – Salud Ocupacional y Ambiente – Salud Ocupacional",
  "Ingeniería en Tecnología de Alimentos – Tecnología de Alimentos",
  "Ingeniería en Tecnologías de Información – Tecnologías de Información",
  "Ingeniería del Software – Tecnologías Informáticas"
];

export default carreras;
